/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ReceiptTokenRouteImport } from './routes/receipt.$token'
import { Route as PortalWigsRouteImport } from './routes/portal.wigs'
import { Route as PortalVerifyRouteImport } from './routes/portal.verify'
import { Route as PortalSignupRouteImport } from './routes/portal.signup'
import { Route as PortalRepairsRouteImport } from './routes/portal.repairs'
import { Route as PortalProfileRouteImport } from './routes/portal.profile'
import { Route as PortalPaymentsRouteImport } from './routes/portal.payments'
import { Route as PortalMessagesRouteImport } from './routes/portal.messages'
import { Route as PortalLoginRouteImport } from './routes/portal.login'
import { Route as PortalAppointmentsRouteImport } from './routes/portal.appointments'
import { Route as AuthenticatedWorkflowsRouteImport } from './routes/_authenticated/workflows'
import { Route as AuthenticatedVendorsRouteImport } from './routes/_authenticated/vendors'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRepairsRouteImport } from './routes/_authenticated/repairs'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated/appointments'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as ApiPublicTwilioStatusRouteImport } from './routes/api/public/twilio-status'
import { Route as ApiPublicTwilioInboundRouteImport } from './routes/api/public/twilio-inbound'
import { Route as ApiPublicSendRemindersRouteImport } from './routes/api/public/send-reminders'
import { Route as ApiPublicResendInboundRouteImport } from './routes/api/public/resend-inbound'
import { Route as ApiPublicResendEventsRouteImport } from './routes/api/public/resend-events'
import { Route as ApiPublicConfirmEmailChangeRouteImport } from './routes/api/public/confirm-email-change'
import { Route as ApiIntuitTokenizeCardRouteImport } from './routes/api/intuit/tokenize-card'
import { Route as ApiIntuitRefundRouteImport } from './routes/api/intuit/refund'
import { Route as ApiIntuitRefreshTokenRouteImport } from './routes/api/intuit/refresh-token'
import { Route as ApiIntuitConnectRouteImport } from './routes/api/intuit/connect'
import { Route as ApiIntuitChargeCardRouteImport } from './routes/api/intuit/charge-card'
import { Route as ApiIntuitCallbackRouteImport } from './routes/api/intuit/callback'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated/settings.users'
import { Route as AuthenticatedSettingsQuickbooksRouteImport } from './routes/_authenticated/settings.quickbooks'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings.notifications'
import { Route as AuthenticatedSettingsClientPortalRouteImport } from './routes/_authenticated/settings.client-portal'
import { Route as AuthenticatedSettingsCalendarRouteImport } from './routes/_authenticated/settings.calendar'
import { Route as AuthenticatedSettingsAuditLogRouteImport } from './routes/_authenticated/settings.audit-log'
import { Route as AuthenticatedInboxNewBroadcastRouteImport } from './routes/_authenticated/inbox.new-broadcast'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ReceiptTokenRoute = ReceiptTokenRouteImport.update({
  id: '/receipt/$token',
  path: '/receipt/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalWigsRoute = PortalWigsRouteImport.update({
  id: '/wigs',
  path: '/wigs',
  getParentRoute: () => PortalRoute,
} as any)
const PortalVerifyRoute = PortalVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSignupRoute = PortalSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => PortalRoute,
} as any)
const PortalRepairsRoute = PortalRepairsRouteImport.update({
  id: '/repairs',
  path: '/repairs',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPaymentsRoute = PortalPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMessagesRoute = PortalMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAppointmentsRoute = PortalAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => PortalRoute,
} as any)
const AuthenticatedWorkflowsRoute = AuthenticatedWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVendorsRoute = AuthenticatedVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRepairsRoute = AuthenticatedRepairsRouteImport.update({
  id: '/repairs',
  path: '/repairs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const ApiPublicTwilioStatusRoute = ApiPublicTwilioStatusRouteImport.update({
  id: '/api/public/twilio-status',
  path: '/api/public/twilio-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioInboundRoute = ApiPublicTwilioInboundRouteImport.update({
  id: '/api/public/twilio-inbound',
  path: '/api/public/twilio-inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendRemindersRoute = ApiPublicSendRemindersRouteImport.update({
  id: '/api/public/send-reminders',
  path: '/api/public/send-reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicResendInboundRoute = ApiPublicResendInboundRouteImport.update({
  id: '/api/public/resend-inbound',
  path: '/api/public/resend-inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicResendEventsRoute = ApiPublicResendEventsRouteImport.update({
  id: '/api/public/resend-events',
  path: '/api/public/resend-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConfirmEmailChangeRoute =
  ApiPublicConfirmEmailChangeRouteImport.update({
    id: '/api/public/confirm-email-change',
    path: '/api/public/confirm-email-change',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntuitTokenizeCardRoute = ApiIntuitTokenizeCardRouteImport.update({
  id: '/api/intuit/tokenize-card',
  path: '/api/intuit/tokenize-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntuitRefundRoute = ApiIntuitRefundRouteImport.update({
  id: '/api/intuit/refund',
  path: '/api/intuit/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntuitRefreshTokenRoute = ApiIntuitRefreshTokenRouteImport.update({
  id: '/api/intuit/refresh-token',
  path: '/api/intuit/refresh-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntuitConnectRoute = ApiIntuitConnectRouteImport.update({
  id: '/api/intuit/connect',
  path: '/api/intuit/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntuitChargeCardRoute = ApiIntuitChargeCardRouteImport.update({
  id: '/api/intuit/charge-card',
  path: '/api/intuit/charge-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntuitCallbackRoute = ApiIntuitCallbackRouteImport.update({
  id: '/api/intuit/callback',
  path: '/api/intuit/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsQuickbooksRoute =
  AuthenticatedSettingsQuickbooksRouteImport.update({
    id: '/quickbooks',
    path: '/quickbooks',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsClientPortalRoute =
  AuthenticatedSettingsClientPortalRouteImport.update({
    id: '/client-portal',
    path: '/client-portal',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsCalendarRoute =
  AuthenticatedSettingsCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAuditLogRoute =
  AuthenticatedSettingsAuditLogRouteImport.update({
    id: '/audit-log',
    path: '/audit-log',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedInboxNewBroadcastRoute =
  AuthenticatedInboxNewBroadcastRouteImport.update({
    id: '/new-broadcast',
    path: '/new-broadcast',
    getParentRoute: () => AuthenticatedInboxRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/inbox': typeof AuthenticatedInboxRouteWithChildren
  '/inventory': typeof AuthenticatedInventoryRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/repairs': typeof AuthenticatedRepairsRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/vendors': typeof AuthenticatedVendorsRoute
  '/workflows': typeof AuthenticatedWorkflowsRoute
  '/portal/appointments': typeof PortalAppointmentsRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/payments': typeof PortalPaymentsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/repairs': typeof PortalRepairsRoute
  '/portal/signup': typeof PortalSignupRoute
  '/portal/verify': typeof PortalVerifyRoute
  '/portal/wigs': typeof PortalWigsRoute
  '/receipt/$token': typeof ReceiptTokenRoute
  '/portal/': typeof PortalIndexRoute
  '/inbox/new-broadcast': typeof AuthenticatedInboxNewBroadcastRoute
  '/settings/audit-log': typeof AuthenticatedSettingsAuditLogRoute
  '/settings/calendar': typeof AuthenticatedSettingsCalendarRoute
  '/settings/client-portal': typeof AuthenticatedSettingsClientPortalRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/quickbooks': typeof AuthenticatedSettingsQuickbooksRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/api/intuit/callback': typeof ApiIntuitCallbackRoute
  '/api/intuit/charge-card': typeof ApiIntuitChargeCardRoute
  '/api/intuit/connect': typeof ApiIntuitConnectRoute
  '/api/intuit/refresh-token': typeof ApiIntuitRefreshTokenRoute
  '/api/intuit/refund': typeof ApiIntuitRefundRoute
  '/api/intuit/tokenize-card': typeof ApiIntuitTokenizeCardRoute
  '/api/public/confirm-email-change': typeof ApiPublicConfirmEmailChangeRoute
  '/api/public/resend-events': typeof ApiPublicResendEventsRoute
  '/api/public/resend-inbound': typeof ApiPublicResendInboundRoute
  '/api/public/send-reminders': typeof ApiPublicSendRemindersRoute
  '/api/public/twilio-inbound': typeof ApiPublicTwilioInboundRoute
  '/api/public/twilio-status': typeof ApiPublicTwilioStatusRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/inbox': typeof AuthenticatedInboxRouteWithChildren
  '/inventory': typeof AuthenticatedInventoryRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/repairs': typeof AuthenticatedRepairsRoute
  '/vendors': typeof AuthenticatedVendorsRoute
  '/workflows': typeof AuthenticatedWorkflowsRoute
  '/portal/appointments': typeof PortalAppointmentsRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/payments': typeof PortalPaymentsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/repairs': typeof PortalRepairsRoute
  '/portal/signup': typeof PortalSignupRoute
  '/portal/verify': typeof PortalVerifyRoute
  '/portal/wigs': typeof PortalWigsRoute
  '/receipt/$token': typeof ReceiptTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/portal': typeof PortalIndexRoute
  '/inbox/new-broadcast': typeof AuthenticatedInboxNewBroadcastRoute
  '/settings/audit-log': typeof AuthenticatedSettingsAuditLogRoute
  '/settings/calendar': typeof AuthenticatedSettingsCalendarRoute
  '/settings/client-portal': typeof AuthenticatedSettingsClientPortalRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/quickbooks': typeof AuthenticatedSettingsQuickbooksRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/api/intuit/callback': typeof ApiIntuitCallbackRoute
  '/api/intuit/charge-card': typeof ApiIntuitChargeCardRoute
  '/api/intuit/connect': typeof ApiIntuitConnectRoute
  '/api/intuit/refresh-token': typeof ApiIntuitRefreshTokenRoute
  '/api/intuit/refund': typeof ApiIntuitRefundRoute
  '/api/intuit/tokenize-card': typeof ApiIntuitTokenizeCardRoute
  '/api/public/confirm-email-change': typeof ApiPublicConfirmEmailChangeRoute
  '/api/public/resend-events': typeof ApiPublicResendEventsRoute
  '/api/public/resend-inbound': typeof ApiPublicResendInboundRoute
  '/api/public/send-reminders': typeof ApiPublicSendRemindersRoute
  '/api/public/twilio-inbound': typeof ApiPublicTwilioInboundRoute
  '/api/public/twilio-status': typeof ApiPublicTwilioStatusRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRouteWithChildren
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/repairs': typeof AuthenticatedRepairsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/vendors': typeof AuthenticatedVendorsRoute
  '/_authenticated/workflows': typeof AuthenticatedWorkflowsRoute
  '/portal/appointments': typeof PortalAppointmentsRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/payments': typeof PortalPaymentsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/repairs': typeof PortalRepairsRoute
  '/portal/signup': typeof PortalSignupRoute
  '/portal/verify': typeof PortalVerifyRoute
  '/portal/wigs': typeof PortalWigsRoute
  '/receipt/$token': typeof ReceiptTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/_authenticated/inbox/new-broadcast': typeof AuthenticatedInboxNewBroadcastRoute
  '/_authenticated/settings/audit-log': typeof AuthenticatedSettingsAuditLogRoute
  '/_authenticated/settings/calendar': typeof AuthenticatedSettingsCalendarRoute
  '/_authenticated/settings/client-portal': typeof AuthenticatedSettingsClientPortalRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/quickbooks': typeof AuthenticatedSettingsQuickbooksRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/api/intuit/callback': typeof ApiIntuitCallbackRoute
  '/api/intuit/charge-card': typeof ApiIntuitChargeCardRoute
  '/api/intuit/connect': typeof ApiIntuitConnectRoute
  '/api/intuit/refresh-token': typeof ApiIntuitRefreshTokenRoute
  '/api/intuit/refund': typeof ApiIntuitRefundRoute
  '/api/intuit/tokenize-card': typeof ApiIntuitTokenizeCardRoute
  '/api/public/confirm-email-change': typeof ApiPublicConfirmEmailChangeRoute
  '/api/public/resend-events': typeof ApiPublicResendEventsRoute
  '/api/public/resend-inbound': typeof ApiPublicResendInboundRoute
  '/api/public/send-reminders': typeof ApiPublicSendRemindersRoute
  '/api/public/twilio-inbound': typeof ApiPublicTwilioInboundRoute
  '/api/public/twilio-status': typeof ApiPublicTwilioStatusRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/portal'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/appointments'
    | '/clients'
    | '/inbox'
    | '/inventory'
    | '/payments'
    | '/profile'
    | '/repairs'
    | '/settings'
    | '/vendors'
    | '/workflows'
    | '/portal/appointments'
    | '/portal/login'
    | '/portal/messages'
    | '/portal/payments'
    | '/portal/profile'
    | '/portal/repairs'
    | '/portal/signup'
    | '/portal/verify'
    | '/portal/wigs'
    | '/receipt/$token'
    | '/portal/'
    | '/inbox/new-broadcast'
    | '/settings/audit-log'
    | '/settings/calendar'
    | '/settings/client-portal'
    | '/settings/notifications'
    | '/settings/quickbooks'
    | '/settings/users'
    | '/api/intuit/callback'
    | '/api/intuit/charge-card'
    | '/api/intuit/connect'
    | '/api/intuit/refresh-token'
    | '/api/intuit/refund'
    | '/api/intuit/tokenize-card'
    | '/api/public/confirm-email-change'
    | '/api/public/resend-events'
    | '/api/public/resend-inbound'
    | '/api/public/send-reminders'
    | '/api/public/twilio-inbound'
    | '/api/public/twilio-status'
    | '/settings/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/appointments'
    | '/clients'
    | '/inbox'
    | '/inventory'
    | '/payments'
    | '/profile'
    | '/repairs'
    | '/vendors'
    | '/workflows'
    | '/portal/appointments'
    | '/portal/login'
    | '/portal/messages'
    | '/portal/payments'
    | '/portal/profile'
    | '/portal/repairs'
    | '/portal/signup'
    | '/portal/verify'
    | '/portal/wigs'
    | '/receipt/$token'
    | '/'
    | '/portal'
    | '/inbox/new-broadcast'
    | '/settings/audit-log'
    | '/settings/calendar'
    | '/settings/client-portal'
    | '/settings/notifications'
    | '/settings/quickbooks'
    | '/settings/users'
    | '/api/intuit/callback'
    | '/api/intuit/charge-card'
    | '/api/intuit/connect'
    | '/api/intuit/refresh-token'
    | '/api/intuit/refund'
    | '/api/intuit/tokenize-card'
    | '/api/public/confirm-email-change'
    | '/api/public/resend-events'
    | '/api/public/resend-inbound'
    | '/api/public/send-reminders'
    | '/api/public/twilio-inbound'
    | '/api/public/twilio-status'
    | '/settings'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/portal'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/appointments'
    | '/_authenticated/clients'
    | '/_authenticated/inbox'
    | '/_authenticated/inventory'
    | '/_authenticated/payments'
    | '/_authenticated/profile'
    | '/_authenticated/repairs'
    | '/_authenticated/settings'
    | '/_authenticated/vendors'
    | '/_authenticated/workflows'
    | '/portal/appointments'
    | '/portal/login'
    | '/portal/messages'
    | '/portal/payments'
    | '/portal/profile'
    | '/portal/repairs'
    | '/portal/signup'
    | '/portal/verify'
    | '/portal/wigs'
    | '/receipt/$token'
    | '/_authenticated/'
    | '/portal/'
    | '/_authenticated/inbox/new-broadcast'
    | '/_authenticated/settings/audit-log'
    | '/_authenticated/settings/calendar'
    | '/_authenticated/settings/client-portal'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/quickbooks'
    | '/_authenticated/settings/users'
    | '/api/intuit/callback'
    | '/api/intuit/charge-card'
    | '/api/intuit/connect'
    | '/api/intuit/refresh-token'
    | '/api/intuit/refund'
    | '/api/intuit/tokenize-card'
    | '/api/public/confirm-email-change'
    | '/api/public/resend-events'
    | '/api/public/resend-inbound'
    | '/api/public/send-reminders'
    | '/api/public/twilio-inbound'
    | '/api/public/twilio-status'
    | '/_authenticated/settings/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ReceiptTokenRoute: typeof ReceiptTokenRoute
  ApiIntuitCallbackRoute: typeof ApiIntuitCallbackRoute
  ApiIntuitChargeCardRoute: typeof ApiIntuitChargeCardRoute
  ApiIntuitConnectRoute: typeof ApiIntuitConnectRoute
  ApiIntuitRefreshTokenRoute: typeof ApiIntuitRefreshTokenRoute
  ApiIntuitRefundRoute: typeof ApiIntuitRefundRoute
  ApiIntuitTokenizeCardRoute: typeof ApiIntuitTokenizeCardRoute
  ApiPublicConfirmEmailChangeRoute: typeof ApiPublicConfirmEmailChangeRoute
  ApiPublicResendEventsRoute: typeof ApiPublicResendEventsRoute
  ApiPublicResendInboundRoute: typeof ApiPublicResendInboundRoute
  ApiPublicSendRemindersRoute: typeof ApiPublicSendRemindersRoute
  ApiPublicTwilioInboundRoute: typeof ApiPublicTwilioInboundRoute
  ApiPublicTwilioStatusRoute: typeof ApiPublicTwilioStatusRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/receipt/$token': {
      id: '/receipt/$token'
      path: '/receipt/$token'
      fullPath: '/receipt/$token'
      preLoaderRoute: typeof ReceiptTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/wigs': {
      id: '/portal/wigs'
      path: '/wigs'
      fullPath: '/portal/wigs'
      preLoaderRoute: typeof PortalWigsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/verify': {
      id: '/portal/verify'
      path: '/verify'
      fullPath: '/portal/verify'
      preLoaderRoute: typeof PortalVerifyRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/signup': {
      id: '/portal/signup'
      path: '/signup'
      fullPath: '/portal/signup'
      preLoaderRoute: typeof PortalSignupRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/repairs': {
      id: '/portal/repairs'
      path: '/repairs'
      fullPath: '/portal/repairs'
      preLoaderRoute: typeof PortalRepairsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/payments': {
      id: '/portal/payments'
      path: '/payments'
      fullPath: '/portal/payments'
      preLoaderRoute: typeof PortalPaymentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/messages': {
      id: '/portal/messages'
      path: '/messages'
      fullPath: '/portal/messages'
      preLoaderRoute: typeof PortalMessagesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/appointments': {
      id: '/portal/appointments'
      path: '/appointments'
      fullPath: '/portal/appointments'
      preLoaderRoute: typeof PortalAppointmentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_authenticated/workflows': {
      id: '/_authenticated/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AuthenticatedWorkflowsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vendors': {
      id: '/_authenticated/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AuthenticatedVendorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/repairs': {
      id: '/_authenticated/repairs'
      path: '/repairs'
      fullPath: '/repairs'
      preLoaderRoute: typeof AuthenticatedRepairsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/api/public/twilio-status': {
      id: '/api/public/twilio-status'
      path: '/api/public/twilio-status'
      fullPath: '/api/public/twilio-status'
      preLoaderRoute: typeof ApiPublicTwilioStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio-inbound': {
      id: '/api/public/twilio-inbound'
      path: '/api/public/twilio-inbound'
      fullPath: '/api/public/twilio-inbound'
      preLoaderRoute: typeof ApiPublicTwilioInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-reminders': {
      id: '/api/public/send-reminders'
      path: '/api/public/send-reminders'
      fullPath: '/api/public/send-reminders'
      preLoaderRoute: typeof ApiPublicSendRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/resend-inbound': {
      id: '/api/public/resend-inbound'
      path: '/api/public/resend-inbound'
      fullPath: '/api/public/resend-inbound'
      preLoaderRoute: typeof ApiPublicResendInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/resend-events': {
      id: '/api/public/resend-events'
      path: '/api/public/resend-events'
      fullPath: '/api/public/resend-events'
      preLoaderRoute: typeof ApiPublicResendEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/confirm-email-change': {
      id: '/api/public/confirm-email-change'
      path: '/api/public/confirm-email-change'
      fullPath: '/api/public/confirm-email-change'
      preLoaderRoute: typeof ApiPublicConfirmEmailChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/intuit/tokenize-card': {
      id: '/api/intuit/tokenize-card'
      path: '/api/intuit/tokenize-card'
      fullPath: '/api/intuit/tokenize-card'
      preLoaderRoute: typeof ApiIntuitTokenizeCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/intuit/refund': {
      id: '/api/intuit/refund'
      path: '/api/intuit/refund'
      fullPath: '/api/intuit/refund'
      preLoaderRoute: typeof ApiIntuitRefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/intuit/refresh-token': {
      id: '/api/intuit/refresh-token'
      path: '/api/intuit/refresh-token'
      fullPath: '/api/intuit/refresh-token'
      preLoaderRoute: typeof ApiIntuitRefreshTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/intuit/connect': {
      id: '/api/intuit/connect'
      path: '/api/intuit/connect'
      fullPath: '/api/intuit/connect'
      preLoaderRoute: typeof ApiIntuitConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/intuit/charge-card': {
      id: '/api/intuit/charge-card'
      path: '/api/intuit/charge-card'
      fullPath: '/api/intuit/charge-card'
      preLoaderRoute: typeof ApiIntuitChargeCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/intuit/callback': {
      id: '/api/intuit/callback'
      path: '/api/intuit/callback'
      fullPath: '/api/intuit/callback'
      preLoaderRoute: typeof ApiIntuitCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/quickbooks': {
      id: '/_authenticated/settings/quickbooks'
      path: '/quickbooks'
      fullPath: '/settings/quickbooks'
      preLoaderRoute: typeof AuthenticatedSettingsQuickbooksRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/client-portal': {
      id: '/_authenticated/settings/client-portal'
      path: '/client-portal'
      fullPath: '/settings/client-portal'
      preLoaderRoute: typeof AuthenticatedSettingsClientPortalRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/calendar': {
      id: '/_authenticated/settings/calendar'
      path: '/calendar'
      fullPath: '/settings/calendar'
      preLoaderRoute: typeof AuthenticatedSettingsCalendarRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/audit-log': {
      id: '/_authenticated/settings/audit-log'
      path: '/audit-log'
      fullPath: '/settings/audit-log'
      preLoaderRoute: typeof AuthenticatedSettingsAuditLogRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/inbox/new-broadcast': {
      id: '/_authenticated/inbox/new-broadcast'
      path: '/new-broadcast'
      fullPath: '/inbox/new-broadcast'
      preLoaderRoute: typeof AuthenticatedInboxNewBroadcastRouteImport
      parentRoute: typeof AuthenticatedInboxRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedInboxRouteChildren {
  AuthenticatedInboxNewBroadcastRoute: typeof AuthenticatedInboxNewBroadcastRoute
}

const AuthenticatedInboxRouteChildren: AuthenticatedInboxRouteChildren = {
  AuthenticatedInboxNewBroadcastRoute: AuthenticatedInboxNewBroadcastRoute,
}

const AuthenticatedInboxRouteWithChildren =
  AuthenticatedInboxRoute._addFileChildren(AuthenticatedInboxRouteChildren)

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAuditLogRoute: typeof AuthenticatedSettingsAuditLogRoute
  AuthenticatedSettingsCalendarRoute: typeof AuthenticatedSettingsCalendarRoute
  AuthenticatedSettingsClientPortalRoute: typeof AuthenticatedSettingsClientPortalRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsQuickbooksRoute: typeof AuthenticatedSettingsQuickbooksRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAuditLogRoute: AuthenticatedSettingsAuditLogRoute,
  AuthenticatedSettingsCalendarRoute: AuthenticatedSettingsCalendarRoute,
  AuthenticatedSettingsClientPortalRoute:
    AuthenticatedSettingsClientPortalRoute,
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRoute,
  AuthenticatedSettingsQuickbooksRoute: AuthenticatedSettingsQuickbooksRoute,
  AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRouteWithChildren
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRepairsRoute: typeof AuthenticatedRepairsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedVendorsRoute: typeof AuthenticatedVendorsRoute
  AuthenticatedWorkflowsRoute: typeof AuthenticatedWorkflowsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRouteWithChildren,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRepairsRoute: AuthenticatedRepairsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedVendorsRoute: AuthenticatedVendorsRoute,
  AuthenticatedWorkflowsRoute: AuthenticatedWorkflowsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PortalRouteChildren {
  PortalAppointmentsRoute: typeof PortalAppointmentsRoute
  PortalLoginRoute: typeof PortalLoginRoute
  PortalMessagesRoute: typeof PortalMessagesRoute
  PortalPaymentsRoute: typeof PortalPaymentsRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalRepairsRoute: typeof PortalRepairsRoute
  PortalSignupRoute: typeof PortalSignupRoute
  PortalVerifyRoute: typeof PortalVerifyRoute
  PortalWigsRoute: typeof PortalWigsRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAppointmentsRoute: PortalAppointmentsRoute,
  PortalLoginRoute: PortalLoginRoute,
  PortalMessagesRoute: PortalMessagesRoute,
  PortalPaymentsRoute: PortalPaymentsRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalRepairsRoute: PortalRepairsRoute,
  PortalSignupRoute: PortalSignupRoute,
  PortalVerifyRoute: PortalVerifyRoute,
  PortalWigsRoute: PortalWigsRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ReceiptTokenRoute: ReceiptTokenRoute,
  ApiIntuitCallbackRoute: ApiIntuitCallbackRoute,
  ApiIntuitChargeCardRoute: ApiIntuitChargeCardRoute,
  ApiIntuitConnectRoute: ApiIntuitConnectRoute,
  ApiIntuitRefreshTokenRoute: ApiIntuitRefreshTokenRoute,
  ApiIntuitRefundRoute: ApiIntuitRefundRoute,
  ApiIntuitTokenizeCardRoute: ApiIntuitTokenizeCardRoute,
  ApiPublicConfirmEmailChangeRoute: ApiPublicConfirmEmailChangeRoute,
  ApiPublicResendEventsRoute: ApiPublicResendEventsRoute,
  ApiPublicResendInboundRoute: ApiPublicResendInboundRoute,
  ApiPublicSendRemindersRoute: ApiPublicSendRemindersRoute,
  ApiPublicTwilioInboundRoute: ApiPublicTwilioInboundRoute,
  ApiPublicTwilioStatusRoute: ApiPublicTwilioStatusRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
